[tool.poetry]
name = "alexlib"
version = "0.2.0"
description = ""
authors = ["Alex Beckwith <57322567+witzbeck@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "*"
python-dotenv = "*"
decorator = "*"
sqlalchemy = "*"
sqlalchemy-utils = "*"
psycopg = "*"
matplotlib = "*"
cryptography = "*"
scipy = "^1.11.4"
scikit-learn = "^1.3.2"

[tool.poetry.group.dev.dependencies]
pytest = "*"
coverage = "*"
ipykernel = "*"
notebook = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
