[tool.poetry]
name = "alexlib"
version = "0.1.0"
description = ""
authors = ["Alex Beckwith <57322567+witzbeck@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11rc1"
pandas = "^2.0.3"
python-dotenv = "^1.0.0"
decorator = "^5.1.1"
setuptools = "^68.0.0"
jupyter = "^1.0.0"
jedi-language-server = "^0.41.0"
jupyterlab = "^4.0.5"
datashader = "^0.15.2"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.25.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
