[tool.poetry]
name = "alexlib"
version = "1.0.0"
description = "A toolset for data science, machine learning, and data engineering."
authors = ["Alex Beckwith <57322567+witzbeck@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.2"
sqlalchemy = "^2.0"
sqlalchemy-utils = "^0.41"
psycopg = "^3.1"
matplotlib = "^3.7"
cryptography = "^42.0"
scipy = "^1.12"
scikit-learn = "^1.4"
reportlab = "^4.0"
pillow = "^10.2"
openai = "^1.14"
pyarrow = "^15.0"
requests = "^2.31"
statsmodels = "^0.14.1"
psycopg-binary = "^3.1.18"
datashader = "^0.16.0"

[tool.poetry.group.test.dependencies]
sqlfluff = "^3.0"
pytest = "^8.1"
pytest-cov = "^4.1"
pytest-mock = "^3.12"
pytest-xdist = "^3.5"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29"

[tool.pytest.ini_options]
addopts = [
    "--cov=alexlib", 
    "--cov-report=term-missing", 
    "--cov-fail-under=60", 
    "--cov-branch"
]
testpaths = ["tests"]

[tool.sqlfluff.core]
verbose = 0
dialect = "postgres"
sql_file_exts = ".sql"
max_line_length = 120
processes = 0
rules = "core"

[tool.sqlfluff.layout.type.comma]
line_position = "leading"
spacing_before = "touch"

[tool.sqlfluff.indentation]
indent_unit = "space"
indented_then = false
indented_joins = true
trailing_comments = "after"

[tool.sqlfluff.layout.type.alias_expression]
spacing_before = "align"
align_scope = "file"

[tool.sqlfluff.capitalisation]
capitalisation_policy = "lower"

[tool.sqlfluff.rules.aliasing.table]
aliasing = "implicit"

[tool.sqlfluff.rules.aliasing.column]
aliasing = "implicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
