[tool.poetry]
name = "alexlib"
version = "0.2.0"
description = ""
authors = ["Alex Beckwith <57322567+witzbeck@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.0.3"
python-dotenv = "^1.0.0"
decorator = "^5.1.1"
sqlalchemy = "^2.0.20"
sqlalchemy-utils = "^0.41.1"
psycopg = "^3.1.10"
matplotlib = "^3.8.2"
cryptography = "^41.0.7"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
coverage = "^7.3.1"
ipykernel = "^6.25.0"
notebook = "^7.0.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
