[tool.poetry]
name = "alexlib"
version = "0.2.0"
description = "A toolset for data science, machine learning, and data engineering."
authors = ["Alex Beckwith <57322567+witzbeck@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "*"
python-dotenv = "*"
decorator = "*"
sqlalchemy = "*"
sqlalchemy-utils = "*"
psycopg-binary = "*"
psycopg = "*"
matplotlib = "*"
cryptography = "*"
scipy = "*"
scikit-learn = "*"
pre-commit = "^3.6.0"
pytest = "^7.4.4"
reportlab = "^4.0.9"
pillow = "^10.2.0"
pylint = "^3.0.3"
openai = "^1.8.0"
pyarrow = "^15.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "*"
coverage = "*"
ipykernel = "*"
notebook = "*"
pytest-cov = "^4.1.0"

[tool.sqlfluff.core]
dialect = "postgres"

[tool.sqlfluff.rules]
indent_unit = "space"
max_line_length = 120
comma_style = "leading"

[tool.sqlfluff.indentation]
use_vertical_hanging_indent = true

[tool.sqlfluff.layout]
align_comments = true
align_aliases = true
align_joins = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
