[tool.poetry]
name = "alexlib"
version = "0.2.0"
description = "A toolset for data science, machine learning, and data engineering."
authors = ["Alex Beckwith <57322567+witzbeck@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "*"
python-dotenv = "*"
decorator = "*"
sqlalchemy = "*"
sqlalchemy-utils = "*"
psycopg-binary = "*"
psycopg = "*"
matplotlib = "*"
cryptography = "*"
scipy = "*"
scikit-learn = "*"
reportlab = "^4.0.9"
pillow = "^10.2.0"
openai = "^1.8.0"
pyarrow = "^15.0.0"

[tool.poetry.group.test.dependencies]
pytest = "*"
pytest-cov = "*"
pytest-mock = "*"
pytest-xdist = "*"

[tool.sqlfluff.core]
verbose = 2
dialect = "postgres"
sql_file_exts = ".sql"
max_line_length = 120
processes = 0
rules = "core"

[tool.sqlfluff.layout.type.comma]
line_position = "leading"
spacing_before = "touch"

[tool.sqlfluff.indentation]
indent_unit = "space"
indented_then = false
indented_joins = true
trailing_comments = "after"

[tool.sqlfluff.layout.type.alias_expression]
spacing_before = "align"
align_scope = "file"

[tool.sqlfluff.capitalisation]
capitalisation_policy = "lower"

[tool.sqlfluff.rules.aliasing.table]
aliasing = "implicit"

[tool.sqlfluff.rules.aliasing.column]
aliasing = "implicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
