apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: alexlib-runner-deployment
  namespace: actions-runners
spec:
  replicas: 3
  template:
    spec:
      repository: witzbeck/alexlib
      labels:
        - self-hosted
        - kubernetes
        - python
      containers:
        - name: runner
          image: ghcr.io/summerwind/actions-runner:latest
          env:
            - name: RUNNER_NAME
              value: "alexlib-runner-$(POD_NAME)"
            - name: RUNNER_LABELS
              value: "self-hosted,kubernetes,python"
            - name: RUNNER_GROUP
              value: "Default"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
