apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: alexlib-runner-deployment
  namespace: actions-runner-system
spec:
  replicas: 3
  template:
    spec:
      repository: witzbeck/alexlib
      containers:
        - name: runner
          image: ghcr.io/summerwind/actions-runner:latest
      labels:
        - self-hosted
        - kubernetes
        - python
