apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: alexlib-runner-deployment
  namespace: actions-runner-system
spec:
  replicas: 2
  template:
    spec:
      repository: witzbeck/alexlib
