name: Python project workflow

on:
  pull_request:
    branches: [ next/* ]

jobs:
  build:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        python-version: ['3.12', '3.11']

    steps:
    # ---------------------------------------------
    # Checkout repository
    # ---------------------------------------------
    - uses: actions/checkout@v4
      name: Checkout repository
      with:
        fetch-depth: 0
    
    # ---------------------------------------------
    # Set up Python
    # ---------------------------------------------
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    # ---------------------------------------------
    # install poetry
    # ---------------------------------------------
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    
    # ---------------------------------------------
    # load cached poetry dependencies if available
    # ---------------------------------------------
    - name: Load cached virtualenv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-
    
    #----------------------------------------------
    # Check the poetry lock file
    #----------------------------------------------
    - name: Install dependencies
      run: poetry check
    
      #----------------------------------------------
    # install dependencies if cache does not exist
    #----------------------------------------------
    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --with test --no-interaction --no-root
    
    #----------------------------------------------
    # install your root project, if required
    #----------------------------------------------
    - name: Install project
      run: poetry install --with test --no-interaction
    
    #----------------------------------------------
    # run test suite
    #----------------------------------------------
    - name: Run tests
      run: |
        poetry run pytest --cov=alexlib --cov-fail-under=75 -n auto
