name: Update Poetry Lock

on:
  pull_request:
    branches:
      - main
    paths:
      - 'pyproject.toml'
    types: [opened, synchronize]

jobs:
  update-lock-file:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Configure Poetry
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry config virtualenvs.create false

      - name: Update lock file
        run: |
          poetry lock --no-update  # Generates an updated lockfile without installing packages

      - name: Commit and push the updated lock file
        run: |
          git config --global user.name 'dependabot[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add poetry.lock
          git commit -m "workflow: Update poetry.lock"
          git push
