name: Test Runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: arc-runner-set
    steps:
      - name: Run a simple command
        run: echo "Hello from Kubernetes runner!"
