name: Test Runner

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: arc-runner-set-alexlib
    steps:
      - name: Run a simple command
        run: echo "Hello from Kubernetes runner!"
